server:
  port: 8888
spring:
  application:
    name: erudio-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jailton2255/erudio-config-server.git
          #username: 
          #password:
          default-label: main
          search-paths:
          - 'greeting-service*' 